name: Terraform EC2 Pipeline

on:
  push:                # run on any commit to any branch
  workflow_dispatch:   # optional manual trigger

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::051404302525:role/Trust-policy-Dev
          aws-region: ap-southeast-2
          audience: sts.amazonaws.com

      - name: Terraform Init (Dev)
        run: terraform init
        working-directory: Environments/Dev

      - name: Terraform Plan (Dev)
        run: terraform plan -input=false
        working-directory: Environments/Dev

      - name: Terraform Apply (Dev)
        run: terraform apply -auto-approve -input=false
        working-directory: Environments/Dev

  terraform-prod:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::051404302525:role/Trust-policy-for-Prod
          aws-region: ap-southeast-2
          audience: sts.amazonaws.com

      - name: Terraform Init (Prod)
        run: terraform init
        working-directory: Environments/Prod

      - name: Terraform Plan (Prod)
        run: terraform plan -input=false
        working-directory: Environments/Prod

      - name: Terraform Apply (Prod)
        run: terraform apply -auto-approve -input=false
        working-directory: Environments/Prod
